type TemporalConnection {
    namespace: String!
    taskQueue: String
}
type AppInfo {
    temporal: TemporalConnection!
    name: String!
}

type CurrentWorkflowState {
    value: String!
    validation: ValidateResponse
    applicationMutation1: MutateApplicationResponse
    applicationMutation2: MutateApplicationResponse
    compensation: CompensateResponse
    reply: ReplyResponse
    beginning: BeginResponse
    finalizable: String
    finalization: FinalizeResponse
    workflowId: String!
}

type Scenarios {
    scenarios: [Scenario!]!
}
type Scenario {
    id: String!
    title: String!
    active: Boolean!
    applicationFailure: String
    exception: String
    value: String
}
type ScenarioDefinitions {
    definitions: [ScenarioDefinition!]!
}
type ScenarioDefinition {
    id: String!
    title: String!
    applicationFailure: String
    exception: String
}

input StartWorkflowRequest {
    workflowId: String!
    value: String!
    reply: ReplyRequest
}

input ValidateRequest {
    value: String!
}
type ValidateResponse {
    value: String!
}

input MutateApplicationRequest {
    value: String!
}
type MutateApplicationResponse {
    value: String!
}

input CompensateRequest {
    value: String!
}
type CompensateResponse {
    value: String!
}

input ReplyRequest {
    value: String!
    taskQueue: String!
    activityName: String!
}
type ReplyResponse {
    workflowId: String!
    id: String!
    value: String!
}

input BeginRequest {
    value: String!
}
type BeginResponse {
    value: String!
}

input MarkFinalizableRequest {
    workflowId: String!
    value: String!
}
input FinalizeRequest {
    workflowId: String!
    value: String!
}
type FinalizeResponse {
    workflowId: String!
    value: String!
}

input QueryRequest {
    workflowId: String!
    value: String
}

input WorkflowStateRequest {
    workflowId: String!
}
type QueryResponse {
    value: String!
}

type Mutation {
    startWorkflow(input: StartWorkflowRequest!): ReplyResponse!
    markFinalizable(input: MarkFinalizableRequest!): FinalizeResponse!
}
type Query {
    appInfo: AppInfo!
    queryWorkflow(input: QueryRequest): CurrentWorkflowState!
    scenarioDefinitions: ScenarioDefinitions!
}
type Subscription {
    workflowState(input: WorkflowStateRequest!): CurrentWorkflowState!
}